name: app_book
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  build_runner: ^2.4.9
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  dots_indicator: ^3.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
     - ./.env
     - assets/images/
     - assets/svg/
  

  
  

  
  

  
  
  
  
  
  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Regular.ttf
         - asset: assets/fonts/Inter-Light.ttf
           weight: 300
         - asset: assets/fonts/Inter-SemiBold.ttf
           weight: 600 
         - asset: assets/fonts/Inter-Bold.ttf
           weight: 700
  
  
  
  
  
  
  
  
